version: '3.3'

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=escuela-javascript
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ./.docker/postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
